const test=require("node:test"),assert=require("node:assert/strict");
const {createPluginInstance}=require("../helpers/createPluginInstance");
const {original14Markdown}=require("../fixtures/s8b-m0a-mixed-language-fixtures");

function pluginWith(engine="oaicompat") {
	const plugin=createPluginInstance({callSetLanguages:false,settings:{engines:{translator:engine,backup:"----"},exceptions:{wrapperPairs:['"|"',"\u201c|\u201d",'`|`'],protectedTerms:[]},choices:{received:{input:"auto",output:"zh-CN"},sent:{input:"auto",output:"en"}}},defaults:{choices:{received:{value:{input:"auto",output:"zh-CN"}},sent:{value:{input:"auto",output:"en"}}}}});
	try{plugin.onLoad();}catch{}
	plugin.settings.engines.translator=engine; plugin.getLanguageChoice=(type,place)=>plugin.settings.choices[place][type]; return plugin;
}

test("M3d compatible received gate keeps complete legacy fallback while semantic plan exposes seven natural-language terms",()=>{const plugin=pluginWith(),[,segments]=plugin.removeExceptions(original14Markdown,"received"),contract=plugin.createAtomicSemanticRevisionContract(original14Markdown,{place:"received",targetLanguageId:"zh-CN"}); assert.equal(Object.keys(segments).length,8); const translate=contract.plan.nodes.filter(node=>node.classification==="translate").map(node=>node.raw).join(""),semanticProtected=Object.values(plugin.getAtomicSemanticLocalState(contract).protectedSegments); for(const token of ["Spouse/Dependent","GED","Non-Degree","In-state","Out-of-state","Self-Pay"]) assert.ok(translate.includes(token),token); assert.equal((translate.match(/Non-Degree/g)||[]).length,2); assert.equal(semanticProtected.includes("\u201c4-3\u201d"),true);});
test("M3d unsupported Provider and sent direction remain legacy",()=>{const plugin=pluginWith("googleapi"),[,legacy]=plugin.removeExceptions(original14Markdown,"received"); assert.equal(Object.keys(legacy).length,8); plugin.settings.engines.translator="oaicompat"; const [,sent]=plugin.removeExceptions(original14Markdown,"sent"); assert.equal(Object.keys(sent).length,8); assert.equal(plugin.shouldUseAtomicSemanticRevision("received"),true); assert.equal(plugin.shouldUseAtomicSemanticRevision("sent"),false);});
test("M3d planner serializer validator repair and Workload revision share one atomic gate",()=>{const plugin=pluginWith(),contract=plugin.createAtomicSemanticRevisionContract(original14Markdown,{place:"received",inputLanguageId:"auto",targetLanguageId:"zh-CN"}); assert.equal(contract.enabled,true); assert.equal(contract.semanticRevision,"s8b-p2-v1"); assert.equal(contract.adapter,"typed-json"); assert.equal(Object.prototype.hasOwnProperty.call(JSON.parse(contract.wire),"semanticRevision"),false,"the semantic revision is a client identity and stays off the wire"); assert.equal(JSON.parse(contract.wire).schemaVersion,"segment-json-v2"); assert.equal(contract.workload.fields.semanticRevision,contract.semanticRevision); const translate=contract.plan.nodes.filter(node=>node.classification==="translate"); for(const term of ["Spouse/Dependent","GED","Non-Degree","In-state","Out-of-state","Self-Pay"]) assert.ok(translate.some(node=>node.raw.includes(term)),term); const missing=plugin.validateAtomicSemanticResponse(contract,{segments:[]}),repair=plugin.planAtomicSemanticRepair(contract,missing,{parentSettled:true}); assert.equal(repair.dispatchable,true); assert.equal(repair.replayedSuccessCount,0); assert.ok(repair.requests.length>0); const legacy=pluginWith("googleapi").createAtomicSemanticRevisionContract("Hello",{place:"received"}); assert.equal(legacy.enabled,false);});
test("M3d cache/request configuration changes semantic revision without changing language or reasoning settings",()=>{const plugin=pluginWith(),before=JSON.stringify(plugin.settings.choices),semantic=plugin.getReceivedTranslationConfigurationData("channel"); assert.equal(semantic.providerSemanticRevision,"s8b-p2-v1"); plugin.settings.engines.translator="googleapi"; const legacy=plugin.getReceivedTranslationConfigurationData("channel"); assert.equal(legacy.providerSemanticRevision,"legacy"); assert.equal(JSON.stringify(plugin.settings.choices),before);});
